name: braille-typing-practice
context:
  git:
    url: git@github.com:maccrey/braille_typing_EX.git
    branch: main
app:
  ports:
    - port: 8080
      protocol: http
  env:
    - name: NODE_ENV
      value: production
    - name: PORT
      value: "8080"
    - name: JWT_SECRET
      value: your-jwt-secret-here
  buildCommands:
    - npm ci --prefix backend
    - npm run db:init --prefix backend
  startCommand: npm start --prefix backend